### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by yaacovCR** [yaacovCR/stitch#90]
### Fundamentals
  - [ ] Properly handle root mutation fields (bundling when possible in the same operation)
  - [ ] Work on customization of stitching resolvers (currently we require resolver to be the same as field name)
  - [ ] Layered plans where fields become incrementally accessible
  - [ ] Interface support
  - [ ] Defer/stream
    - [x] Split deferred fragments between different subschemas #71
    - [ ] Enrich deferred results with additional fields from different subschemas
    - [ ] Enrich streamed results

### Validation
  - [ ] Superschema composition errors
  - [ ] Inaccessible field errors (plan failures)

### Testing
  - [ ] add additional tests for mutations/subscriptions/defer/stream/etc/etc/etc/etc/etc

### Benchmarks
  - [ ] add benchmarking for plan creation/execution

### Documentation
  - [ ] add API documentation
  - [ ] add examples
  - [ ] work on tutorial
  - [ ] comparison with other frameworks

### Housekeeping:
  - [ ] Split named fragments across subschemas (instead of converting to inline fragments) #67
  - [ ] Consider not hardcoding total deferred number of payloads into identifier but saving separately as part of plan
